server:
  port: 8080

spring:
  application:
    name: "Solarmaxx"
  datasource:
    url: jdbc:h2:mem:solarmaxx
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

device:
  type:
    url:
      pattern:
        ip: "%IP"
        id: "%ID"
        port: "%PORT"
        toggle: "%TOGGLE"
