
server:
  port: 8080
spring:
  application:
    name: "SolarMAXX"
  datasource:
    url: jdbc:h2:mem:solarmaxx
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always