# Verifies commits, does not generate any artifact

name: Builder

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Extract artifact version
        if: ${{ github.ref_type == 'branch' }}
        run: |
          GRADLE_VERSION=$(./gradlew properties | grep "^version:" | cut -d ":" -f 2 | xargs)
          echo "FINAL_VERSION=$GRADLE_VERSION.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}