# Verifies commits, does not generate any artifact

name: Builder

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Extract artifact version
        if: ${{ github.ref_type == 'branch' }}
        run: |
          GRADLE_VERSION=$(./gradlew properties | grep "^version:" | cut -d ":" -f 2 | xargs)
          echo "FINAL_VERSION=$GRADLE_VERSION.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Create version tag
        if: ${{ github.ref_type == 'branch' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ env.FINAL_VERSION }}`,
              sha: context.sha
            })